function Hd = untitled1
%UNTITLED1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 12-Jan-2016 22:04:43

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 1250;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 1;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
